HerramientaAD/Controllers/TablerosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HerramientaAD.Models;

namespace HerramientaAD.Controllers
{
    public class TablerosController : Controller
    {
        // GET: Tableros
        public ActionResult Index()
        {
            if (Session["UsuarioID"] != null)
            {
                var tableroGeneralModel = new TableroGeneralModel(int.Parse(Session["UsuarioID"].ToString()), 0, 0);

                return View(tableroGeneralModel);
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        public ActionResult Inicial(int AplicacionID)
        {
            if (Session["UsuarioID"] != null)
            {
                var tableroInicialModel = new TableroInicialModel(int.Parse(Session["UsuarioID"].ToString()), 0, AplicacionID);
                ViewBag.Aplicacion = AplicacionID;
                ViewBag.NombreAplicacion = tableroInicialModel.ResultadoXML.InnerXml.Split('\"')[3]; //MMOB
                return View(tableroInicialModel);
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        public ActionResult ResumenHallazgos(int AplicacionID, int BaseDeDatosID)
        {
            if (Session["UsuarioID"] != null)
            {
                var ResumenHallModel = new ResumenHallazgosModel(int.Parse(Session["UsuarioID"].ToString()), BaseDeDatosID, AplicacionID);
                ViewBag.Aplicacion = AplicacionID;
                ViewBag.NombreAplicacion = ResumenHallModel.HallazgosBD.ElementAt(0).NombreApp; //MMOB
                return View(ResumenHallModel);
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }
        public ActionResult ResumenHallazgosDetalle(int AplicacionID, int BaseDeDatosID)
        {
            if (Session["UsuarioID"] != null)
            {
                var ResumenHallModel = new ResumenHallazgosModel(int.Parse(Session["UsuarioID"].ToString()), BaseDeDatosID, AplicacionID);
                ViewBag.Aplicacion = AplicacionID;
                ViewBag.NombreAplicacion = ResumenHallModel.HallazgosBD.ElementAt(0).NombreApp; //MMOB
                return PartialView("ResumenHallazgosDetalle", ResumenHallModel);
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        public ActionResult GrupoBD(int AplicacionID)
        {
            if (Session["UsuarioID"] != null)
            {
                var grupoBDModel = new GrupoBDModel(int.Parse(Session["UsuarioID"].ToString()), AplicacionID);
                ViewBag.Aplicacion = AplicacionID;
                ViewBag.NombreAplicacion = grupoBDModel.Indicadores.ElementAt(0).NombreApp; //MMOB
                return View(grupoBDModel);
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        public ActionResult GrupoBDDetalle(int AplicacionID)
        {
            if (Session["UsuarioID"] != null)
            {
                var grupoBDModel = new GrupoBDModel(int.Parse(Session["UsuarioID"].ToString()), AplicacionID);
                ViewBag.Aplicacion = AplicacionID;
                ViewBag.NombreAplicacion = grupoBDModel.Indicadores.ElementAt(0).NombreApp; //MMOB
                return PartialView("GrupoBDIndicadores", grupoBDModel);
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        public JsonResult CargaDatosGrupoBD(int BaseDeDatosID, int Tipo)
        {
            var datosGrafica = Json("", JsonRequestBehavior.AllowGet);
            if (Session["UsuarioID"] != null)
            {
                var grupoBDModel = new GrupoBDModel(int.Parse(Session["UsuarioID"].ToString()), BaseDeDatosID);
                switch (Tipo)
                {
                    case 1:
                        datosGrafica = Json(grupoBDModel.ArchivosPie, JsonRequestBehavior.AllowGet);
                        break;
                    case 2:
                        datosGrafica = Json(grupoBDModel.ArchivosColumn, JsonRequestBehavior.AllowGet);
                        break;
                    case 3:
                        datosGrafica = Json(grupoBDModel.MasUsados, JsonRequestBehavior.AllowGet);
                        break;
                };
            }
            else
            {
                RedirectToAction("Index", "Login");
            }
            return datosGrafica;
        }

        public ActionResult AnalisisBD(int AplicacionID)
        {
            if (Session["UsuarioID"] != null)
            {
                var analisisBD = new AnalisisBD(int.Parse(Session["UsuarioID"].ToString()), AplicacionID, 0);
                ViewBag.Aplicacion = AplicacionID;
                ViewBag.NombreAplicacion = analisisBD.Indicadores.ElementAt(0).NombreApp; //MMOB
                return View(analisisBD);
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        public ActionResult AnalisisBDDetalle(int AplicacionID)
        {
            if (Session["UsuarioID"] != null)
            {
                var analisisBDModel = new AnalisisBD(int.Parse(Session["UsuarioID"].ToString()), AplicacionID, 1);
                ViewBag.Aplicacion = AplicacionID;
                ViewBag.NombreAplicacion = analisisBDModel.Indicadores.ElementAt(0).NombreApp; //MMOB
                return PartialView("AnalisisBDDetalle", analisisBDModel);
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        public JsonResult CargaDatosAnalisisBD(int BaseDeDatosID, int Tipo)
        {

            var datosGrafica = Json("", JsonRequestBehavior.AllowGet);
            if (Session["UsuarioID"] != null)
            {
                var analisisBDModel = new AnalisisBD(int.Parse(Session["UsuarioID"].ToString()), BaseDeDatosID, 2);
                switch (Tipo)
                {
                    case 1:
                        datosGrafica = Json(analisisBDModel.LlavePrimaria, JsonRequestBehavior.AllowGet);
                        break;
                    case 2:
                        datosGrafica = Json(analisisBDModel.LlaveForanea, JsonRequestBehavior.AllowGet);
                        break;
                    case 3:
                        datosGrafica = Json(analisisBDModel.Indexes, JsonRequestBehavior.AllowGet);
                        break;
                    case 4:
                        datosGrafica = Json(analisisBDModel.TipoObjeto, JsonRequestBehavior.AllowGet);
                        break;
                    case 5:
                        datosGrafica = Json(analisisBDModel.TamanoTabla, JsonRequestBehavior.AllowGet);
                        break;
                    case 6:
                        datosGrafica = Json(analisisBDModel.LineasEfectivas, JsonRequestBehavior.AllowGet);
                        break;
                    case 7:
                        datosGrafica = Json(analisisBDModel.LineasComentadas, JsonRequestBehavior.AllowGet);
                        break;
                    case 8:
                        datosGrafica = Json(analisisBDModel.Select, JsonRequestBehavior.AllowGet);
                        break;
                    case 9:
                        datosGrafica = Json(analisisBDModel.Insert, JsonRequestBehavior.AllowGet);
                        break;
                    case 10:
                        datosGrafica = Json(analisisBDModel.Update, JsonRequestBehavior.AllowGet);
                        break;
                    case 11:
                        datosGrafica = Json(analisisBDModel.Delete, JsonRequestBehavior.AllowGet);
                        break;
                    case 12:
                        datosGrafica = Json(analisisBDModel.Siif, JsonRequestBehavior.AllowGet);
                        break;
                    case 13:
                        datosGrafica = Json(analisisBDModel.Loop, JsonRequestBehavior.AllowGet);
                        break;
                    case 14:
                        datosGrafica = Json(analisisBDModel.Select2, JsonRequestBehavior.AllowGet);
                        break;
                    case 15:
                        datosGrafica = Json(analisisBDModel.Excepcion, JsonRequestBehavior.AllowGet);
                        break;
                };
            }
            else
            {
                RedirectToAction("Index", "Login");
            }
            return datosGrafica;
        }

        public ActionResult GrupoWS(int AplicacionID)
        {
            if (Session["UsuarioID"] != null)
            {
                var grupoWSModel = new GrupoWSModel(int.Parse(Session["UsuarioID"].ToString()), AplicacionID);
                ViewBag.Aplicacion = AplicacionID;
                ViewBag.NombreAplicacion = grupoWSModel.Indicadores.ElementAt(0).NombreApp; //MMOB
                return View(grupoWSModel);
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }



        public ActionResult GrupoCM(int AplicacionID)
        {
            if (Session["UsuarioID"] != null)
            {
                var grupoCMModel = new GrupoCMModel(int.Parse(Session["UsuarioID"].ToString()), AplicacionID);
                ViewBag.Aplicacion = AplicacionID;
                ViewBag.NombreAplicacion = grupoCMModel.Indicadores.ElementAt(0).NombreApp; //MMOB
                return View(grupoCMModel);
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

HerramientaAD/Views/Tableros/AnalisisCM.cshtml
@model HerramientaAD.Models.AnalisisCMModel

@{
    ViewBag.Title = "AnalisisCM";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Concept Map</title>
    <meta name="description" content="A concept map diagram implemented with labeled links and ForceDirectedLayout." />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="~/Estilos/Loader.css" rel="stylesheet" />
    <script src="~/Scripts/Loader.js"></script>

    <script src="~/Scripts/go.js"></script>
    <script type="text/javascript">

        function MostrarLoader() {
            $(".loader").fadeIn();
        }

        function OcultarLoader() {
            $(".loader").fadeOut();
        }
    </script>
    <script id="code">
        function init() {

            var Datos = [];

            Datos.push({ key: "0", name: "@Model.Aplicacion", type: "Tipo", color: "Color", description: "Descripcion" });

            @{
                foreach (HerramientaAD.com.Utilerias.ElementosDiagramaCM.Cuadros diagramaCM in Model.DiagramaCM)
                {
                    if (@diagramaCM.Llave != "")
                    {
 @:Datos.push({ key: "@diagramaCM.Llave", parent: "@diagramaCM.Padre", name: "@diagramaCM.Nombre", type: "@diagramaCM.Tipo", color: "@diagramaCM.Color", description: "@diagramaCM.Descripcion" });
                    }

                }
            }

            var $ = go.GraphObject.make;  // for conciseness in defining templates

            myDiagram =
                $(go.Diagram, "myDiagramDiv",  // must be the ID or reference to div
                    {
                        "toolManager.hoverDelay": 100,  // 100 milliseconds instead of the default 850
                        allowCopy: false,
                        layout:  // create a TreeLayout for the family tree
                            $(go.TreeLayout,
                                { angle: 90, nodeSpacing: 10, layerSpacing: 40, layerStyle: go.TreeLayout.LayerUniform })
                    });

            var bluegrad = "#90CAF9";
            var pinkgrad = "#F48FB1";

                     // get tooltip text from the object's data
            function tooltipTextConverter(person) {
                var str = "";
                str += "Línea: " + person.description;
                //if (person.deathYear !== undefined) str += "\nDied: " + person.deathYear;
                //if (person.reign !== undefined) str += "\nReign: " + person.reign;
                return str;
            }

            // define tooltips for nodes
            var tooltiptemplate =
                $("ToolTip",
                    { "Border.fill": "whitesmoke", "Border.stroke": "black" },
                    $(go.TextBlock,
                        {
                            font: "bold 8pt Helvetica, bold Arial, sans-serif",
                            wrap: go.TextBlock.WrapFit,
                            margin: 5
                        },
                        new go.Binding("text", "", tooltipTextConverter))
                );

            // define Converters to be used for Bindings
            function genderBrushConverter(type) {
                if (type === "ARCHIVO") return "#84A7D0";
                if (type === "CLASE") return "#A693BD";
                return "#E15953";
            }

            // replace the default Node template in the nodeTemplateMap
            myDiagram.nodeTemplate =
                $(go.Node, "Auto",
                    { deletable: false, toolTip: tooltiptemplate },
                    new go.Binding("text", "name"),
                    $(go.Shape, "Rectangle",
                        {
                            fill: "lightgray",
                            stroke: null, strokeWidth: 0,
                            stretch: go.GraphObject.Fill,
                            alignment: go.Spot.Center
                        },
                        new go.Binding("fill", "type", genderBrushConverter)),
                    $(go.TextBlock,
                        {
                            font: "700 12px Droid Serif, sans-serif",
                            textAlign: "center",
                            margin: 10, maxSize: new go.Size(80, NaN)
                        },
                        new go.Binding("text", "name"))
                );

            // define the Link template
            myDiagram.linkTemplate =
                $(go.Link,  // the whole link panel
                    { routing: go.Link.Orthogonal, corner: 5, selectable: false },
                    $(go.Shape, { strokeWidth: 3, stroke: '#424242' }));  // the gray link shape

            // here's the family data
            var nodeDataArray = Datos;

            // create the model for the family tree
            myDiagram.model = new go.TreeModel(nodeDataArray);

            document.getElementById('zoomToFit').addEventListener('click', function () {
                myDiagram.zoomToFit();
            });

            document.getElementById('centerRoot').addEventListener('click', function () {
                myDiagram.scale = 1;
                myDiagram.scrollToRect(myDiagram.findNodeForKey(0).actualBounds);
            });

        }
    </script>

</head>
<body onload="init(), OcultarLoader()">
    <div class="jumbotron">
        <h1 class="display-3">@Model.DiagramaCM.ElementAt(0).NombreApp</h1>
        <p class="lead">Resultados del Análisis de Clases, Funciones y Métodos</p>
        <hr class="my-4">
    </div>
    <div id="divLoader" class="loader"></div>
    <div class="alert alert-dismissible alert-primary">
        <h6 class="mb-0">Diagrama de los elementos que componen la aplicación y las relaciones que comparten cada uno de estos elementos con otros.</h6>
    </div>
    <div class="card border-secondary mb-3" style="max-width: 20rem;">
        <div class="card-header">Tipos</div>
        <div class="card-body">
            <table>
                <tr>
                    <td style="background:#E15953" width="30px"></td>
                    <td width="5px"></td>
                    <td style="font-size:17px">Aplicación</td>
                </tr>
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td style="background:#84A7D0"></td>
                    <td></td>
                    <td style="font-size:17px">Archivos</td>
                </tr>
                <tr>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td style="background:#A693BD"></td>
                    <td></td>
                    <td style="font-size:17px">Clases</td>
                </tr>
            </table>
        </div>
    </div>


    <div id="sample" data-toggle="tooltip" title="ZOOM, 1.- Da click sobre el diagrama. 2.- ctrl + para aumentar o crtl  - para disminuir.">
        <div id="myDiagramDiv" style="background-color: white; border: solid 1px black; width: 100%; height: 450px"></div>
        <br />
        <p><button class="btn btn-primary" id="zoomToFit">Alejar zoom</button> <button class="btn btn-primary" id="centerRoot">Ir al centro</button></p>
        <br />
    </div>

    <div class="alert alert-dismissible alert-primary">
        <h6 class="alert-heading">Zoom</h6>
        <h6 class="mb-0">1.- Dar click sobre el diagrama. <br />2.- <strong>ctrl +</strong> para aumentar o <strong>ctrl -</strong> para disminuir.</h6>
    </div>

</body>
</html>

HerramientaAD/Views/Tableros/DiagramaUML.cshtml
@model HerramientaAD.Models.DiagramaUMLModel
@{
    ViewBag.Title = "DiagramaUML";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Concept Map</title>
    <meta name="description" content="A concept map diagram implemented with labeled links and ForceDirectedLayout." />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Copyright 1998-2019 by Northwoods Software Corporation. -->

    <script src="~/Scripts/go.js"></script>

    <script id="code">
        function init() {
            if (window.goSamples) goSamples();  // init for these samples -- you don't need to call this
            var $ = go.GraphObject.make;  // for conciseness in defining templates
            myDiagram =
                $(go.Diagram, "myDiagramDiv",  // must name or refer to the DIV HTML element
                    {
                        initialAutoScale: go.Diagram.Uniform,  // an initial automatic zoom-to-fit
                        contentAlignment: go.Spot.Center,  // align document to the center of the viewport
                        layout:
                            $(go.ForceDirectedLayout,  // automatically spread nodes apart
                                { maxIterations: 200, defaultSpringLength: 30, defaultElectricalCharge: 100 })
                    });
            // define each Node's appearance
            myDiagram.nodeTemplate =
                $(go.Node, "Auto",  // the whole node panel
                    { locationSpot: go.Spot.Center },
                    // define the node's outer shape, which will surround the TextBlock
                    $(go.Shape, "Rectangle",
                        { fill: $(go.Brush, "Linear", { 0: "rgb(254, 201, 0)", 1: "rgb(254, 162, 0)" }), stroke: "black" }),
                    $(go.TextBlock,
                        { font: "bold 10pt helvetica, bold arial, sans-serif", margin: 4 },
                        new go.Binding("text", "text"))
                );
            // replace the default Link template in the linkTemplateMap
            myDiagram.linkTemplate =
                $(go.Link,  // the whole link panel
                    $(go.Shape,  // the link shape
                        { stroke: "black" }),
                    $(go.Shape,  // the arrowhead
                        { toArrow: "standard", stroke: null }),
                    $(go.Panel, "Auto",
                        $(go.Shape,  // the label background, which becomes transparent around the edges
                            {
                                fill: $(go.Brush, "Radial", { 0: "rgb(240, 240, 240)", 0.3: "rgb(240, 240, 240)", 1: "rgba(240, 240, 240, 0)" }),
                                stroke: null
                            }),
                        $(go.TextBlock,  // the label text
                            {
                                textAlign: "center",
                                font: "10pt helvetica, arial, sans-serif",
                                stroke: "#555555",
                                margin: 4
                            },
                            new go.Binding("text", "text"))
                    )
                );
            // create the model for the concept map
            var nodeDataArray = [
                { key: 1, text: "Concept Maps" },
                { key: 2, text: "Organized Knowledge" },
                { key: 3, text: "Context Dependent" },
                { key: 4, text: "Concepts" },
                { key: 5, text: "Propositions" },
                { key: 6, text: "Associated Feelings or Affect" },
                { key: 7, text: "Perceived Regularities" },
                { key: 8, text: "Labeled" },
                { key: 9, text: "Hierarchically Structured" },
                { key: 10, text: "Effective Teaching" },
                { key: 11, text: "Crosslinks" },
                { key: 12, text: "Effective Learning" },
                { key: 13, text: "Events (Happenings)" },
                { key: 14, text: "Objects (Things)" },
                { key: 15, text: "Symbols" },
                { key: 16, text: "Words" },
                { key: 17, text: "Creativity" },
                { key: 18, text: "Interrelationships" },
                { key: 19, text: "Infants" },
                { key: 20, text: "Different Map Segments" }
            ];
            var linkDataArray = [
                { from: 1, to: 2, text: "represent" },
                { from: 2, to: 3, text: "is" },
                { from: 2, to: 4, text: "is" },
                { from: 2, to: 5, text: "is" },
                { from: 2, to: 6, text: "includes" },
                { from: 2, to: 10, text: "necessary\nfor" },
                { from: 2, to: 12, text: "necessary\nfor" },
                { from: 4, to: 5, text: "combine\nto form" },
                { from: 4, to: 6, text: "include" },
                { from: 4, to: 7, text: "are" },
                { from: 4, to: 8, text: "are" },
                { from: 4, to: 9, text: "are" },
                { from: 5, to: 9, text: "are" },
                { from: 5, to: 11, text: "may be" },
                { from: 7, to: 13, text: "in" },
                { from: 7, to: 14, text: "in" },
                { from: 7, to: 19, text: "begin\nwith" },
                { from: 8, to: 15, text: "with" },
                { from: 8, to: 16, text: "with" },
                { from: 9, to: 17, text: "aids" },
                { from: 11, to: 18, text: "show" },
                { from: 12, to: 19, text: "begins\nwith" },
                { from: 17, to: 18, text: "needed\nto see" },
                { from: 18, to: 20, text: "between" }
            ];
            myDiagram.model = new go.GraphLinksModel(nodeDataArray, linkDataArray);
        }
    </script>
</head>
<body onload="init()">

    <div class="jumbotron">
        <h1 class="display-3">@Model.Indicadores.ElementAt(0).NombreApp</h1>
        <p class="lead">Resultados del diagrama de UML</p>
        <hr class="my-4">
    </div>

    <div id="sample">
        <div id="myDiagramDiv" style="background-color: whitesmoke; border: solid 1px black; width: 100%; height: 700px"></div>
        <p>
            A concept map sample depicting various suggested relationships between different ideas.
            See also the <a href="interactiveForce.html">Interactive Force</a> sample that uses the exact same data
            but a different node template and an interactive <a>ForceDirectedLayout</a>.
        </p>
    </div>
</body>
</html>

HerramientaAD/Views/Tableros/GrupoBDDetalle.cshtml
@model HerramientaAD.Models.GrupoBDModel

<table width="100%" class="table-simple">
    <tr class="table-primary">
        <td colspan="2" align="center">
            <p style="font-size:20px; font-weight:bold">Estadísticas de objetos encontrados por Tipo de Archivo</p>
        </td>
    <tr>
        <td style="padding:20px">
            <div id="graficaArchivosColumnas" style="height: 370px;" />
        </td>
        <td style="padding:20px">
            <div id="graficaArchivosPie" style="height: 370px;" />
        </td>
    </tr>
    <tr class="table-primary">
        <td colspan="2" align="center">
            <p style="font-size:20px; font-weight:bold">Lista de los 10 objetos más utilizados dentro del Código</p>
        </td>
    </tr>
    <tr>
        <td colspan="2" style="padding:20px">
            <div id="graficaMasUsados" style="height: 370px; width: 100%;" />
        </td>
    </tr>
</table>

<script src="~/Scripts/canvasjs.min.js"></script>
<script>
    function initBD(graficaArchivosPie, graficaArchivosColumnas, graficaMasUsados) {

        var Datos = graficaArchivosPie;

        var chart = new CanvasJS.Chart("graficaArchivosPie", {
            exportEnabled: true,
            animationEnabled: true,
            title: {
                text: "Tipos de Archivos Analizados",
                fontFamily: "Segoe UI"
            },
            legend: {
                cursor: "pointer",
                itemclick: explodePie
            },
            data: [{
                type: "pie",
                showInLegend: false,
                toolTipContent: "{name}: <strong>{y}%</strong>",
                indexLabel: "{name} - {y}%",
                dataPoints: Datos
            }]
        });
        chart.render();
        Datos = graficaArchivosColumnas;

        var chart = new CanvasJS.Chart("graficaArchivosColumnas", {
            animationEnabled: true,
            theme: "light2",
            title: {
                text: "Objetos Encontrados",
                fontFamily: "Segoe UI",
                fontWeight: "normal"
            },
            axisY: {
                title: "Número de Objetos"
            },
            data: [{
                type: "column",
                showInLegend: false,
                legendMarkerColor: "grey",
                dataPoints: Datos
            }]
        });
        chart.render();
        Datos = graficaMasUsados;

        var chart = new CanvasJS.Chart("graficaMasUsados", {
	        animationEnabled: true,
            exportEnabled: true,
	        title:{
                text: "Elementos sobresalientes",
                fontFamily: "Segoe UI"
	        },
	        axisX:{
		        interval: 1
	        },
	        axisY2:{
		        interlacedColor: "rgba(1,77,101,.2)",
		        gridColor: "rgba(1,77,101,.1)",
		        title: "Objetos de Base de Datos"
	        },
	        data: [{
                type: "bar",
		        name: "objetos",
		        axisYType: "secondary",
		        color: "#014D65",
		        dataPoints: Datos
	        }]
        });
        chart.render();
        Datos = [];
    }

    function explodePie(e) {
        if (typeof (e.dataSeries.dataPoints[e.dataPointIndex].exploded) === "undefined" || !e.dataSeries.dataPoints[e.dataPointIndex].exploded) {
            e.dataSeries.dataPoints[e.dataPointIndex].exploded = true;
        } else {
            e.dataSeries.dataPoints[e.dataPointIndex].exploded = false;
        }
        e.chart.render();
    }
</script>

HerramientaAD/Views/Tableros/Index.cshtml
@model HerramientaAD.Models.TableroGeneralModel

@{
    ViewBag.Title = "Tablero General";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="jumbotron">
    <h1 class="display-3">Tablero General</h1>
    <p class="lead">Aplicaciones analizadas</p>
    <hr class="my-4">
</div>
<div class="alert alert-dismissible alert-primary">
    <h6>Listado de aplicaciones analizadas, selecciona una aplicación para ver su detalle.</h6>
</div>


<table class="table table-bordered">
    <thead>
    </thead>
    <tbody>
        @{
            foreach (System.Xml.XmlNode xmlNode in Model.ResultadoXML.DocumentElement.SelectSingleNode("Aplicaciones").SelectNodes("row"))
            {
                <tr>
                    <td>
                        <table class="table table-borderless">
                            <tbody>
                                <tr>
                                    <td width="35%">@xmlNode.Attributes["AplicacionDescripcion"].Value.ToString()</td>
                                    <td width="15%">
                                        @Html.ActionLink(xmlNode.Attributes["Aplicacion"].Value.ToString(), "Inicial", "Tableros",
                                   new { AplicacionID = xmlNode.Attributes["AplicacionID"].Value }, null)
                                    </td>
                                    <td><strong>Criticidad:</strong> </td>
                                    <td>@xmlNode.Attributes["Criticidad"].Value.ToString()</td>
                                    <td><img width="20" height="20" src="@Url.Content(xmlNode.Attributes["CriticidadImagen"].Value.ToString())" /></td>
                                    <td><strong>Proceso:</strong></td>
                                    <td>@xmlNode.Attributes["Proceso"].Value.ToString()</td>
                                    <td><img width="20" height="20" src="@Url.Content(xmlNode.Attributes["ProcesoImagen"].Value.ToString())" /></td>
                                </tr>
                                <tr>
                                    <td><strong>Última Actualización: </strong>@xmlNode.Attributes["UltimaActualizacion"].Value.ToString()</td>
                                    <td></td>
                                    <td><strong>Lenguaje: </strong></td>
                                    <td>@xmlNode.Attributes["Lenguaje"].Value.ToString()</td>
                                    <td><img width="20" height="20" src="@Url.Content(xmlNode.Attributes["LenguajeImagen"].Value.ToString())" /></td>
                                    <td><strong>Estatus: </strong></td>
                                    <td>@xmlNode.Attributes["Estatus"].Value.ToString()</td>
                                    <td><img width="20" height="20" src="@Url.Content(xmlNode.Attributes["EstatusImagen"].Value.ToString())" /></td>
                                </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>


@*<br />
<div class="alert alert-dismissible alert-primary">
    <h6 class="alert-heading">Indicaciones</h6>
    <h6>Ver resultados del análisis de alguna aplicación</h6>
    <h6 class="mb-0">1.- Dar click sobre uno de los nombres en azul de alguna aplicación. </h6>
    <h6 class="mb-0">2.- Mostrará el tablero de la aplicación elegida. </h6>
    <h6 class="mb-0">3.- Navegar sobre el menú desplegable. </h6>
</div>
<br />*@